### ISSUE TITLE
data-v-equal hangs page

### ISSUE THREAD

**Issue by sapabg** [emretulek/jbvalidator#6]
Hello,
I have a little problem with data-v-equal 
I have 2 inputs - password and confirm and I want the second to be the same as the first (pretty standart, right...)...
When you type in the password and there is nothing in confirm there is no problem but if you have any text in confirm and then type something in password or change the password value the whole page hangs. Something it bounces back and 'wakes up' but it takes a ton of time. You can see the same behaviour in the demo page: [https://emretulek.github.io/jbvalidator/](https://emretulek.github.io/jbvalidator/)
Try filling something in 'equal - rePassword' than start typing in password and it hangs at some point.

**Comment by emretulek** [comment]
You are right, after a few tries it was starting to crash. Now the problem is solved, you can try again here. 
https://emretulek.github.io/jbvalidator/

**Comment by sapabg** [comment]
Alright, when I use the CDN <script src="https://cdn.jsdelivr.net/npm/@emretulek/jbvalidator"></script>it works.
For some reason it didn't work when I downloaded it. I saw that the sizes are 1KB different but it still hanged...I'll use the CDN...

**Comment by emretulek** [comment]
There may be an issue with the cache. The file sizes look the same to me (7.96kb), I could not see any difference.
